
package com.jc.ws.first;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import first.com.jc.ws.FirstInfoProcessImplService;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2019-08-31T17:55:54.801+09:00
 * Generated source version: 2.6.2
 * 
 */
public final class FirstInfoProcess_FirstInfoPort_Client {

    private static final QName SERVICE_NAME = new QName("ws.jc.com.first", "FirstInfoProcessImplService");

    private FirstInfoProcess_FirstInfoPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FirstInfoProcessImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        FirstInfoProcessImplService ss = new FirstInfoProcessImplService(wsdlURL, SERVICE_NAME);
        FirstInfoProcess port = ss.getFirstInfoPort();  
        
        {
        System.out.println("Invoking processFirst...");
        com.jc.ws.first.FirstVo _processFirst__return = port.processFirst();
        System.out.println("processFirst.result=" + _processFirst__return);


        }

        System.exit(0);
    }

}
