
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.jc.ws.first;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2019-08-31T17:55:54.840+09:00
 * Generated source version: 2.6.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "FirstInfoProcessImplService",
                      portName = "firstInfoPort",
                      targetNamespace = "ws.jc.com.first",
                      wsdlLocation = "file:/D:/KJC/workSpace/TestCom/src/main/webapp/WEB-INF/FirstInfo.wsdl",
                      endpointInterface = "com.jc.ws.first.FirstInfoProcess")
                      
public class FirstInfoProcessImpl implements FirstInfoProcess {

    private static final Logger LOG = Logger.getLogger(FirstInfoProcessImpl.class.getName());

    /* (non-Javadoc)
     * @see com.jc.ws.first.FirstInfoProcess#processFirst(*
     */
    public com.jc.ws.first.FirstVo processFirst() { 
        LOG.info("Executing operation processFirst");
        try {
            com.jc.ws.first.FirstVo _return = new com.jc.ws.first.FirstVo();
            _return.setUser("User1849901190");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
