package first.com.jc.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.jc.ws.first.FirstInfoProcess;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2019-08-31T17:55:54.851+09:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "FirstInfoProcessImplService", 
                  wsdlLocation = "file:/D:/KJC/workSpace/TestCom/src/main/webapp/WEB-INF/FirstInfo.wsdl",
                  targetNamespace = "ws.jc.com.first") 
public class FirstInfoProcessImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("ws.jc.com.first", "FirstInfoProcessImplService");
    public final static QName FirstInfoPort = new QName("ws.jc.com.first", "firstInfoPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/KJC/workSpace/TestCom/src/main/webapp/WEB-INF/FirstInfo.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FirstInfoProcessImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/KJC/workSpace/TestCom/src/main/webapp/WEB-INF/FirstInfo.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FirstInfoProcessImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FirstInfoProcessImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FirstInfoProcessImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FirstInfoProcessImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FirstInfoProcessImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FirstInfoProcessImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns FirstInfoProcess
     */
    @WebEndpoint(name = "firstInfoPort")
    public FirstInfoProcess getFirstInfoPort() {
        return super.getPort(FirstInfoPort, FirstInfoProcess.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FirstInfoProcess
     */
    @WebEndpoint(name = "firstInfoPort")
    public FirstInfoProcess getFirstInfoPort(WebServiceFeature... features) {
        return super.getPort(FirstInfoPort, FirstInfoProcess.class, features);
    }

}
